name: Build and Publish MAUI App

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Build the project
      run: |
        dotnet build --configuration Release

    - name: Publish the app
      run: |
        dotnet publish --configuration Release --output ./publish --self-contained true -r win-x64

    - name: Replace appsettings.json with appsettings.template.json
      run: |
        # Remove the appsettings.json file if it exists
        Remove-Item -Path "./publish/appsettings.json" -Force -ErrorAction SilentlyContinue
        # Copy the appsettings.template.json to the publish directory
        Copy-Item -Path "./appsettings.template.json" -Destination "./publish/appsettings.json"

    - name: Create GitHub release
      uses: ghenaoi/create-release-action@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: 'Release notes for version ${{ github.ref }}'

    - name: Upload the release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./publish/*.exe
          ./publish/appsettings.json  # Only includes the template version

    - name: Clean up
      run: |
        # Clean up build files (optional)
        Remove-Item -Recurse -Force ./publish
